# Generated by Django 4.2.10 on 2024-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopWordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('top_words', models.JSONField(null=True)),
                ('n', models.IntegerField()),
            ],
        ),
    ]
